version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: prewave-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prewave
      POSTGRES_PASSWORD: prewave
      POSTGRES_DB: prewave_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prewave -d prewave_db"]
      interval: 10s
      timeout: 5s
      retries: 5
