version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: prewave-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prewave
      POSTGRES_PASSWORD: prewave
      POSTGRES_DB: prewave_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prewave -d prewave_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prewave-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prewave-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prewave_db
      SPRING_DATASOURCE_USERNAME: prewave
      SPRING_DATASOURCE_PASSWORD: prewave
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prewave-network

networks:
  prewave-network:
    driver: bridge
